myfile1 = open("marks.dat", "r")
myfile2 = open("Otherfile.dat", "w+")
l = myfile1.readlines()
print("The content of the Source file : " , l)
myfile2.writelines(l)
myfile1.close()
myfile2.seek(0)
content = myfile2.readlines()
print("The content of the destination file : " , content)